### PR TITLE
Fix the class reroll (everything this time)

### PR DESCRIPTION
**Pull request by palette-dev**
I've fixed all the still broken class names
(I'm so sorry for the duplicate PR, I messed up and didn't want to pull useless commits into your repo)

### CODE REVIEW

**Comment by githubguy217** [comment]
please let this be accepted, i want this theme to finally be fixed

**Comment by sparkle8205** [comment]
Hey this theme broke again, I just wanted to let you know. I'm also not great at using github so i apologise if this is not the right place to comment this. The original theme finally broke for me today despite it being ages since it was last updated, so I went to try yours and it has also been broken. I require this theme due to my sensory issue n stuff so thought I'd let you know.. (this may not be the right place to put it, but alas this is the only way i can reach out it seems.)

**Comment by jh34ghu43gu** [comment]
Oh sorry everyone I didn't get notifications for this. They changed all the names again though so I don't think this pull will work. Please @ me if you decide to make a future request and hopefully I'll get an email for that.

I will continue updating this repo to keep fixing reacts and mentions everytime they break for me (which may have a 1 week delay since my client only updates about that often @sparkle8205 ). Those are the only two things that really bother me about the new theme (and the bot "app" icons but those appear to be new and I'm not sure what the old color was).

**Comment by palette-dev** [comment]
Ah okay I didn't notice they broke css classes again, I'll fix it today after I'm off work

**Pull request closed without merging**
